/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const getEmployee = /* GraphQL */ `
  query GetEmployee($id: ID!) {
    getEmployee(id: $id) {
      id
      first_name
      last_name
      email
      phone
      CompanyOfEmployee {
        id
        name
        location
        employee_count
        Employees {
          items {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        documents {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        Contractors {
          items {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        employee_handbook
        hr_policies
        laws
        companyLogoURL
        labor_posters
        employee_handbook_questions
        google_drive
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      birthdate
      DocumentsForEmployee {
        items {
          id
          Type
          fileName
          url
          isSigned
          contractorID
          employeeID
          companyID
          DocumentForContractor {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForEmployee {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForCompany {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          isSent
          sign_url
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        nextToken
        startedAt
      }
      location
      position
      address
      emergency_contact_name
      emergency_contact_relation
      emergency_contact_email
      emergency_contact_phone
      hasSignature
      companyID
      city
      state
      zip
      id_docs
      ListA_image
      ListB_image
      ListC_image
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`
export const listEmployees = /* GraphQL */ `
  query ListEmployees($filter: ModelEmployeeFilterInput, $limit: Int, $nextToken: String) {
    listEmployees(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        first_name
        last_name
        email
        phone
        CompanyOfEmployee {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        birthdate
        DocumentsForEmployee {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        companyID
        city
        state
        zip
        id_docs
        ListA_image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const syncEmployees = /* GraphQL */ `
  query SyncEmployees($filter: ModelEmployeeFilterInput, $limit: Int, $nextToken: String, $lastSync: AWSTimestamp) {
    syncEmployees(filter: $filter, limit: $limit, nextToken: $nextToken, lastSync: $lastSync) {
      items {
        id
        first_name
        last_name
        email
        phone
        CompanyOfEmployee {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        birthdate
        DocumentsForEmployee {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        companyID
        city
        state
        zip
        id_docs
        ListA_image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const getContractor = /* GraphQL */ `
  query GetContractor($id: ID!) {
    getContractor(id: $id) {
      id
      first_name
      last_name
      email
      phone
      birthdate
      CompanyOfContractor {
        id
        name
        location
        employee_count
        Employees {
          items {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        documents {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        Contractors {
          items {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        employee_handbook
        hr_policies
        laws
        companyLogoURL
        labor_posters
        employee_handbook_questions
        google_drive
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      DocumentsForContractor {
        items {
          id
          Type
          fileName
          url
          isSigned
          contractorID
          employeeID
          companyID
          DocumentForContractor {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForEmployee {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForCompany {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          isSent
          sign_url
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        nextToken
        startedAt
      }
      location
      companyID
      position
      address
      emergency_contact_name
      emergency_contact_relation
      emergency_contact_email
      emergency_contact_phone
      hasSignature
      city
      state
      zip
      id_docs
      ListA_Image
      ListB_image
      ListC_image
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`
export const listContractors = /* GraphQL */ `
  query ListContractors($filter: ModelContractorFilterInput, $limit: Int, $nextToken: String) {
    listContractors(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        first_name
        last_name
        email
        phone
        birthdate
        CompanyOfContractor {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentsForContractor {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        companyID
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        city
        state
        zip
        id_docs
        ListA_Image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const syncContractors = /* GraphQL */ `
  query SyncContractors($filter: ModelContractorFilterInput, $limit: Int, $nextToken: String, $lastSync: AWSTimestamp) {
    syncContractors(filter: $filter, limit: $limit, nextToken: $nextToken, lastSync: $lastSync) {
      items {
        id
        first_name
        last_name
        email
        phone
        birthdate
        CompanyOfContractor {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentsForContractor {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        companyID
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        city
        state
        zip
        id_docs
        ListA_Image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const getDocument = /* GraphQL */ `
  query GetDocument($id: ID!) {
    getDocument(id: $id) {
      id
      Type
      fileName
      url
      isSigned
      contractorID
      employeeID
      companyID
      DocumentForContractor {
        id
        first_name
        last_name
        email
        phone
        birthdate
        CompanyOfContractor {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentsForContractor {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        companyID
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        city
        state
        zip
        id_docs
        ListA_Image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      DocumentForEmployee {
        id
        first_name
        last_name
        email
        phone
        CompanyOfEmployee {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        birthdate
        DocumentsForEmployee {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        location
        position
        address
        emergency_contact_name
        emergency_contact_relation
        emergency_contact_email
        emergency_contact_phone
        hasSignature
        companyID
        city
        state
        zip
        id_docs
        ListA_image
        ListB_image
        ListC_image
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      DocumentForCompany {
        id
        name
        location
        employee_count
        Employees {
          items {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        documents {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        Contractors {
          items {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        employee_handbook
        hr_policies
        laws
        companyLogoURL
        labor_posters
        employee_handbook_questions
        google_drive
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      isSent
      sign_url
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`
export const listDocuments = /* GraphQL */ `
  query ListDocuments($filter: ModelDocumentFilterInput, $limit: Int, $nextToken: String) {
    listDocuments(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        Type
        fileName
        url
        isSigned
        contractorID
        employeeID
        companyID
        DocumentForContractor {
          id
          first_name
          last_name
          email
          phone
          birthdate
          CompanyOfContractor {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentsForContractor {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          companyID
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          city
          state
          zip
          id_docs
          ListA_Image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentForEmployee {
          id
          first_name
          last_name
          email
          phone
          CompanyOfEmployee {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          birthdate
          DocumentsForEmployee {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          companyID
          city
          state
          zip
          id_docs
          ListA_image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentForCompany {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        isSent
        sign_url
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const syncDocuments = /* GraphQL */ `
  query SyncDocuments($filter: ModelDocumentFilterInput, $limit: Int, $nextToken: String, $lastSync: AWSTimestamp) {
    syncDocuments(filter: $filter, limit: $limit, nextToken: $nextToken, lastSync: $lastSync) {
      items {
        id
        Type
        fileName
        url
        isSigned
        contractorID
        employeeID
        companyID
        DocumentForContractor {
          id
          first_name
          last_name
          email
          phone
          birthdate
          CompanyOfContractor {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentsForContractor {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          companyID
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          city
          state
          zip
          id_docs
          ListA_Image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentForEmployee {
          id
          first_name
          last_name
          email
          phone
          CompanyOfEmployee {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          birthdate
          DocumentsForEmployee {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          companyID
          city
          state
          zip
          id_docs
          ListA_image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        DocumentForCompany {
          id
          name
          location
          employee_count
          Employees {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          documents {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          Contractors {
            items {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          employee_handbook
          hr_policies
          laws
          companyLogoURL
          labor_posters
          employee_handbook_questions
          google_drive
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        isSent
        sign_url
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const getCompany = /* GraphQL */ `
  query GetCompany($id: ID!) {
    getCompany(id: $id) {
      id
      name
      location
      employee_count
      Employees {
        items {
          id
          first_name
          last_name
          email
          phone
          CompanyOfEmployee {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          birthdate
          DocumentsForEmployee {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          companyID
          city
          state
          zip
          id_docs
          ListA_image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        nextToken
        startedAt
      }
      documents {
        items {
          id
          Type
          fileName
          url
          isSigned
          contractorID
          employeeID
          companyID
          DocumentForContractor {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForEmployee {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentForCompany {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          isSent
          sign_url
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        nextToken
        startedAt
      }
      Contractors {
        items {
          id
          first_name
          last_name
          email
          phone
          birthdate
          CompanyOfContractor {
            id
            name
            location
            employee_count
            Employees {
              nextToken
              startedAt
            }
            documents {
              nextToken
              startedAt
            }
            Contractors {
              nextToken
              startedAt
            }
            employee_handbook
            hr_policies
            laws
            companyLogoURL
            labor_posters
            employee_handbook_questions
            google_drive
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          DocumentsForContractor {
            items {
              id
              Type
              fileName
              url
              isSigned
              contractorID
              employeeID
              companyID
              isSent
              sign_url
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            nextToken
            startedAt
          }
          location
          companyID
          position
          address
          emergency_contact_name
          emergency_contact_relation
          emergency_contact_email
          emergency_contact_phone
          hasSignature
          city
          state
          zip
          id_docs
          ListA_Image
          ListB_image
          ListC_image
          createdAt
          updatedAt
          _version
          _deleted
          _lastChangedAt
        }
        nextToken
        startedAt
      }
      employee_handbook
      hr_policies
      laws
      companyLogoURL
      labor_posters
      employee_handbook_questions
      google_drive
      createdAt
      updatedAt
      _version
      _deleted
      _lastChangedAt
    }
  }
`
export const listCompanies = /* GraphQL */ `
  query ListCompanies($filter: ModelCompanyFilterInput, $limit: Int, $nextToken: String) {
    listCompanies(filter: $filter, limit: $limit, nextToken: $nextToken) {
      items {
        id
        name
        location
        employee_count
        Employees {
          items {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        documents {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        Contractors {
          items {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        employee_handbook
        hr_policies
        laws
        companyLogoURL
        labor_posters
        employee_handbook_questions
        google_drive
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
export const syncCompanies = /* GraphQL */ `
  query SyncCompanies($filter: ModelCompanyFilterInput, $limit: Int, $nextToken: String, $lastSync: AWSTimestamp) {
    syncCompanies(filter: $filter, limit: $limit, nextToken: $nextToken, lastSync: $lastSync) {
      items {
        id
        name
        location
        employee_count
        Employees {
          items {
            id
            first_name
            last_name
            email
            phone
            CompanyOfEmployee {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            birthdate
            DocumentsForEmployee {
              nextToken
              startedAt
            }
            location
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            companyID
            city
            state
            zip
            id_docs
            ListA_image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        documents {
          items {
            id
            Type
            fileName
            url
            isSigned
            contractorID
            employeeID
            companyID
            DocumentForContractor {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              companyID
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              city
              state
              zip
              id_docs
              ListA_Image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForEmployee {
              id
              first_name
              last_name
              email
              phone
              birthdate
              location
              position
              address
              emergency_contact_name
              emergency_contact_relation
              emergency_contact_email
              emergency_contact_phone
              hasSignature
              companyID
              city
              state
              zip
              id_docs
              ListA_image
              ListB_image
              ListC_image
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentForCompany {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            isSent
            sign_url
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        Contractors {
          items {
            id
            first_name
            last_name
            email
            phone
            birthdate
            CompanyOfContractor {
              id
              name
              location
              employee_count
              employee_handbook
              hr_policies
              laws
              companyLogoURL
              labor_posters
              employee_handbook_questions
              google_drive
              createdAt
              updatedAt
              _version
              _deleted
              _lastChangedAt
            }
            DocumentsForContractor {
              nextToken
              startedAt
            }
            location
            companyID
            position
            address
            emergency_contact_name
            emergency_contact_relation
            emergency_contact_email
            emergency_contact_phone
            hasSignature
            city
            state
            zip
            id_docs
            ListA_Image
            ListB_image
            ListC_image
            createdAt
            updatedAt
            _version
            _deleted
            _lastChangedAt
          }
          nextToken
          startedAt
        }
        employee_handbook
        hr_policies
        laws
        companyLogoURL
        labor_posters
        employee_handbook_questions
        google_drive
        createdAt
        updatedAt
        _version
        _deleted
        _lastChangedAt
      }
      nextToken
      startedAt
    }
  }
`
