# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest


variables:
  AWS_ACCESS_KEY_ID: PASTE_YOUR_KEY_HERE
  AWS_SECRET_ACCESS_KEY: PASTE_YOUR_SECRET_KEY_HERE

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

# Java tool installer v0
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8' # string. Required. JDK version. Default: 8.
    jdkArchitectureOption: x64 # 'x64' | 'x86'. Required. JDK architecture. 
    jdkSourceOption: PreInstalled

- script: |
    yarn install
  displayName: 'install dependencies'
  workingDirectory: backend

- script: |
    yarn serverless dynamodb install
    yarn serverless dynamodb start &
  displayName: 'install and start dynamodb local'
  workingDirectory: backend


- script: |
    yarn test
  displayName: 'star testing'
  workingDirectory: backend

