service: service-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-dynamodb-local
  - serverless-offline
custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      seed: true
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      convertEmptyValues: true
      online: false
      region: us-east-1

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: graphql/handler.graphqlHandler
    events:
    - http:
        path: /graphql
        method: any
        cors: true

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}