Resources:
  UserIdentity:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-UserIdentity
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-User
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  EmployeeDocumentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-EmployeeDocuments
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: userDocId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: userDocId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  UserActivityTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-UserActivityTable
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: userActivityId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: userActivityId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CavnessDocumentsTable2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-DocumentTable
      AttributeDefinitions:
        - AttributeName: documentType
          AttributeType: S
        - AttributeName: documentId
          AttributeType: S
      KeySchema:
        - AttributeName: documentType
          KeyType: HASH
        - AttributeName: documentId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  DocumentAccessTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-DocumentAccess
      AttributeDefinitions:
        - AttributeName: hashKey
          AttributeType: S
        - AttributeName: documentId
          AttributeType: S
      KeySchema:
        - AttributeName: hashKey
          KeyType: HASH
        - AttributeName: documentId
          KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: documentId
        KeySchema:
          - AttributeName: documentId
            KeyType: HASH
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  DocumentCategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-DocumentCategory
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: categoryText
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: categoryText
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  AccountManagerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-AccountManagerTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: companyId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: companyId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CompanyLocationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-CompanyLocation
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S
        - AttributeName: locationId
          AttributeType: S
      KeySchema:
        - AttributeName: companyId
          KeyType: HASH
        - AttributeName: locationId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  CompanyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}-Company
      AttributeDefinitions:
        - AttributeName: companyId
          AttributeType: S

      KeySchema:
        - AttributeName: companyId
          KeyType: HASH

      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
